# Етап збірки з Maven + OpenJDK 20
FROM maven:3.9.6-openjdk-20 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Етап запуску з OpenJDK 20
FROM openjdk:20-jdk-slim
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
